# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: GOSEEK-Challenge
short_description: Create an RL agent that combines perception and high-level decision-making to search for objects placed within complex indoor environments.
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: True
start_date: 2020-02-15 00:00:00
end_date: 2020-05-01 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["Recall", "Precision", "Collisions", "Actions", "Weighted Total"],
        "default_order_by": "Weighted Total",
      }

challenge_phases:
  - id: 1
    name: Development Phase with Ground Truth
    description: templates/dev-groundtruth.html
    leaderboard_public: False
    is_public: True
    is_submission_public: True
    start_date: 2020-02-15 00:00:00
    end_date: 2020-05-01 23:59:59
    test_annotation_file: annotations/dummy.json
    codename: dev-groundtruth
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 50
  - id: 2
    name: Development Phase with Perception Pipeline
    description: templates/dev-perception.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2020-02-15 00:00:00
    end_date: 2020-05-01 23:59:59
    test_annotation_file: annotations/dummy.json
    codename: dev-perception
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 50
  - id: 3
    name: Competition Phase with Ground Truth
    description: templates/competition-groundtruth.html
    leaderboard_public: False
    is_public: True
    is_submission_public: True
    start_date: 2020-02-15 00:00:00
    end_date: 2020-05-01 23:59:59
    test_annotation_file: annotations/dummy.json
    codename: competition-groundtruth
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 50
  - id: 4
    name: Competition Phase with Perception Pipeline
    description: templates/competition-perception.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2020-02-15 00:00:00
    end_date: 2020-05-01 23:59:59
    test_annotation_file: annotations/dummy.json
    codename: competition-perception
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 50

dataset_splits:
  - id: 1
    name: Withheld Scenes
    codename: withheld_scenes

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 2
    leaderboard_decimal_precision: 3
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 2
    leaderboard_decimal_precision: 3
    is_leaderboard_order_descending: True
  - challenge_phase_id: 3
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 3
    is_leaderboard_order_descending: True
  - challenge_phase_id: 4
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 3
    is_leaderboard_order_descending: True
